import pluginJs from '@eslint/js'
import globals from 'globals'
import { defineConfig } from '../utils/index.js'

export function javascript() {
	return defineConfig([
		{
			name: 'fans/javascript',
			plugins: {
				js: pluginJs,
			},
			languageOptions: {
				ecmaVersion: 2022,
				globals: {
					...globals.browser,
					...globals.node,
					...globals.es2022,
					document: 'readonly',
					navigator: 'readonly',
					window: 'readonly',
				},
				parserOptions: {
					ecmaFeatures: {
						jsx: true,
					},
					ecmaVersion: 2022,
					sourceType: 'module',
				},
				sourceType: 'module',
			},
			linterOptions: {
				reportUnusedDisableDirectives: true,
			},
			rules: {
				'accessor-pairs': 'error',
				'array-callback-return': 'error',
				'block-scoped-var': 'error',
				'class-methods-use-this': 'error',
				'consistent-this': 'error',
				'constructor-super': 'error',
				'curly': ['error', 'all'],
				'default-case-last': 'error',
				'default-param-last': 'error',
				'dot-notation': 'error',
				'eqeqeq': 'error',
				'for-direction': 'error',
				'func-name-matching': 'error',
				'getter-return': 'error',
				'grouped-accessor-pairs': 'error',
				'guard-for-in': 'error',
				'id-denylist': 'error',
				'id-match': 'error',
				'init-declarations': 'error',
				'max-classes-per-file': 'error',
				'max-depth': 'error',
				'max-nested-callbacks': 'error',
				'new-cap': 'error',
				'no-array-constructor': 'error',
				'no-async-promise-executor': 'error',
				'no-bitwise': 'error',
				'no-caller': 'error',
				'no-case-declarations': 'error',
				'no-class-assign': 'error',
				'no-compare-neg-zero': 'error',
				'no-cond-assign': 'error',
				'no-console': ['error', {
					allow: ['warn', 'error'],
				}],
				'no-const-assign': 'error',
				'no-constant-binary-expression': 'error',
				'no-constant-condition': 'error',
				'no-constructor-return': 'error',
				'no-control-regex': 'error',
				'no-debugger': 'error',
				'no-delete-var': 'error',
				'no-div-regex': 'error',
				'no-dupe-args': 'error',
				'no-dupe-class-members': 'error',
				'no-dupe-else-if': 'error',
				'no-dupe-keys': 'error',
				'no-duplicate-case': 'error',
				'no-empty': 'error',
				'no-empty-character-class': 'error',
				'no-empty-function': 'error',
				'no-empty-pattern': 'error',
				'no-empty-static-block': 'error',
				'no-eq-null': 'error',
				'no-eval': 'error',
				'no-ex-assign': 'error',
				'no-extend-native': 'error',
				'no-extra-bind': 'error',
				'no-extra-boolean-cast': 'error',
				'no-extra-label': 'error',
				'no-fallthrough': 'error',
				'no-func-assign': 'error',
				'no-global-assign': 'error',
				'no-implicit-globals': 'error',
				'no-implied-eval': 'error',
				'no-import-assign': 'error',
				'no-inner-declarations': 'error',
				'no-invalid-regexp': 'error',
				'no-invalid-this': 'error',
				'no-iterator': 'error',
				'no-label-var': 'error',
				'no-labels': 'error',
				'no-lone-blocks': 'error',
				'no-lonely-if': 'error',
				'no-loop-func': 'error',
				'no-loss-of-precision': 'error',
				'no-misleading-character-class': 'error',
				'no-multi-assign': 'error',
				'no-multi-str': 'error',
				'no-negated-condition': 'error',
				'no-nested-ternary': 'error',
				'no-new': 'error',
				'no-new-func': 'error',
				'no-new-native-nonconstructor': 'error',
				'no-new-wrappers': 'error',
				'no-nonoctal-decimal-escape': 'error',
				'no-obj-calls': 'error',
				'no-object-constructor': 'error',
				'no-octal': 'error',
				'no-octal-escape': 'error',
				'no-param-reassign': 'error',
				'no-proto': 'error',
				'no-prototype-builtins': 'error',
				'no-redeclare': 'error',
				'no-regex-spaces': 'error',
				'no-restricted-exports': 'error',
				'no-restricted-globals': 'error',
				'no-restricted-imports': 'error',
				'no-restricted-properties': 'error',
				'no-restricted-syntax': 'error',
				'no-return-assign': 'error',
				'no-script-url': 'error',
				'no-self-assign': 'error',
				'no-self-compare': 'error',
				'no-sequences': 'error',
				'no-setter-return': 'error',
				'no-shadow': 'error',
				'no-shadow-restricted-names': 'error',
				'no-sparse-arrays': 'error',
				'no-template-curly-in-string': 'error',
				'no-this-before-super': 'error',
				'no-throw-literal': 'error',
				'no-unassigned-vars': 'error',
				'no-undef': 'error',
				'no-unexpected-multiline': 'error',
				'no-unmodified-loop-condition': 'error',
				'no-unneeded-ternary': 'error',
				'no-unreachable': 'error',
				'no-unreachable-loop': 'error',
				'no-unsafe-finally': 'error',
				'no-unsafe-negation': 'error',
				'no-unsafe-optional-chaining': 'error',
				'no-unused-expressions': 'error',
				'no-unused-labels': 'error',
				'no-unused-private-class-members': 'error',
				'no-unused-vars': 'error',
				'no-useless-backreference': 'error',
				'no-useless-call': 'error',
				'no-useless-catch': 'error',
				'no-useless-concat': 'error',
				'no-useless-constructor': 'error',
				'no-useless-escape': 'error',
				'no-useless-rename': 'error',
				'no-useless-return': 'error',
				'no-var': 'error',
				'no-with': 'error',
				'object-shorthand': 'error',
				'operator-assignment': 'error',
				'prefer-arrow-callback': 'error',
				'prefer-const': ['error', {
					destructuring: 'all',
					ignoreReadBeforeAssign: true,
				}],
				'prefer-exponentiation-operator': 'error',
				'prefer-numeric-literals': 'error',
				'prefer-object-spread': 'error',
				'prefer-promise-reject-errors': 'error',
				'prefer-regex-literals': 'error',
				'prefer-rest-params': 'error',
				'prefer-spread': 'error',
				'require-yield': 'error',
				'sort-vars': 'error',
				'strict': 'error',
				'symbol-description': 'error',
				'unicode-bom': 'error',
				'use-isnan': 'error',
				'valid-typeof': 'error',
				'vars-on-top': 'error',
				'yoda': 'error',
			},
		},
	])
}
