export const GLOB_SRC_EXT: string
export const GLOB_TS: string
export const GLOB_DTS: string
export const GLOB_VUE: string
export const GLOB_ASTRO: string
export const GLOB_ASTRO_PAGES: string
export const GLOB_STORYBOOK: string
export const GLOB_TESTS: string[]
export const GLOB_EXCLUDE: string[]
